"""empty message

Revision ID: 60467539b539
Revises: a199e540d237
Create Date: 2019-05-02 21:48:39.255829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60467539b539'
down_revision = 'a199e540d237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    # ### end Alembic commands ###
